server:
  port: 8080
service:
  environment: local

spring:
  datasource:
    url: jdbc:mysql://localhost:13306?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog_user
    password: blog2022!
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
    generate-ddl: false #
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate.query.plan_cache_max_size: 800
      hibernate.query.plan_parameter_metadata_max_size: 32

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

