server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5


